import { createServerClient } from '@supabase/ssr'
import { createClient } from '@supabase/supabase-js'
import { cookies } from 'next/headers'
import * as Y from 'yjs'

interface EmailPayload {
  id: string
  from: string
  subject: string
  date: string
  snippet: string
  priority: 'HIGH' | 'NORMAL' | 'LOW'
  reason: string
  rank: number
}

function xmlEl(tag: string, attrs: Record<string, string | number> = {}) {
  const el = new Y.XmlElement(tag)
  for (const [k, v] of Object.entries(attrs)) el.setAttribute(k, String(v))
  return el
}

function xmlText(str: string, marks: Record<string, unknown> = {}) {
  const t = new Y.XmlText()
  if (str) t.insert(0, str, Object.keys(marks).length ? marks : undefined)
  return t
}

function para(text: string, marks: Record<string, unknown> = {}) {
  const p = xmlEl('paragraph')
  if (text) p.push([xmlText(text, marks)])
  return p
}

function heading(text: string, level = 1) {
  const h = xmlEl('heading', { level })
  h.push([xmlText(text)])
  return h
}

function bulletList(items: string[]) {
  const ul = xmlEl('bulletList')
  for (const item of items) {
    const li = xmlEl('listItem')
    const p = xmlEl('paragraph')
    p.push([xmlText(item)])
    li.push([p])
    ul.push([li])
  }
  return ul
}

export async function POST(request: Request) {
  const cookieStore = await cookies()
  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll: () => cookieStore.getAll(),
        setAll: (cs) => cs.forEach(({ name, value, options }) => cookieStore.set(name, value, options)),
      },
    }
  )

  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return new Response('Unauthorized', { status: 401 })

  const { emails } = await request.json() as { emails: EmailPayload[] }
  if (!emails?.length) return Response.json({ error: 'No emails provided' }, { status: 400 })

  // Build Yjs document
  const doc = new Y.Doc()
  const frag = doc.getXmlFragment('default')
  const now = new Date()
  const dateStr = now.toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })

  frag.push([heading(`📧 Email Digest — ${dateStr}`, 1)])
  frag.push([para(`${emails.length} unread emails · ranked by priority`)])

  const high   = emails.filter(e => e.priority === 'HIGH')
  const normal = emails.filter(e => e.priority === 'NORMAL')
  const low    = emails.filter(e => e.priority === 'LOW')

  const fmt = (e: EmailPayload) => `${e.subject} — from ${e.from.replace(/<.*>/, '').trim()}`

  if (high.length) {
    frag.push([heading('🔴 High Priority', 2)])
    frag.push([bulletList(high.map(fmt))])
  }
  if (normal.length) {
    frag.push([heading('🟡 Normal Priority', 2)])
    frag.push([bulletList(normal.map(fmt))])
  }
  if (low.length) {
    frag.push([heading('🟢 Low Priority', 2)])
    frag.push([bulletList(low.map(fmt))])
  }

  frag.push([para(`Generated by Nexus · ${now.toISOString()}`)])

  const update = Y.encodeStateAsUpdate(doc)
  const title = `📧 Email Digest — ${now.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}`

  const serviceSupabase = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
  )

  const { data, error } = await serviceSupabase
    .from('docs')
    .insert({
      user_id: user.id,
      title,
      content: Array.from(update),
      text_content: `${emails.length} unread emails. ${high.length} high priority.`,
      icon: '📧',
    })
    .select('id')
    .single()

  if (error) return Response.json({ error: error.message }, { status: 500 })

  return Response.json({ docId: data.id, title })
}
